Repository Simsso/Online-Tools, pull requests merged in 2020-04, with the labels that each got.

#17 Refactor logic in filling matrix for interpolation
  src/page/logic/polynomial-interpolation.js
Labels: refactoring

#16 Home page update
  src/special-page/home.php
Labels: infra

#15 Omitting of very small coefficients in interpolation tool
  src/page/adapter/cubic-spline-interpolation.js
  src/page/adapter/polynomial-interpolation.js
Labels: bug
